"""Reproducible SP 800-53A "Test" procedures executed against (synthetic) evidence.

Each test reads evidence files by EVID ID, applies the documented test logic,
and writes a workpaper (markdown) plus machine-readable results that the
build and the consistency tests consume.

    python tools/assessment_tests.py all
    python tools/assessment_tests.py termination|termination-validation|logreview|vulnsla|changes
"""
from __future__ import annotations

import datetime as dt
import statistics
import sys
from pathlib import Path

from common import META, ROOT, SNAPSHOT, md_table, read_csv, write_json

EV = ROOT / "evidence"
OUT = ROOT / "docs" / "assessment" / "test-results"
SLA_H = META["thresholds"]["deprovision_sla_hours"]


def _ts(date: str, hhmm: str) -> dt.datetime:
    # HR effective times are US/Eastern wall-clock; deactivation events carry offsets.
    # Compare in naive local time: sufficient at hour granularity for a 24h SLA.
    return dt.datetime.fromisoformat(f"{date}T{hhmm}")


def _local(iso: str) -> dt.datetime:
    return dt.datetime.fromisoformat(iso).replace(tzinfo=None)


def _write(name: str, title: str, body: str, result: dict):
    OUT.mkdir(parents=True, exist_ok=True)
    header = (f"# {title}\n\n> Generated by `tools/assessment_tests.py` from synthetic evidence. "
              f"Re-run to re-perform the test. Status date {META['status_date']}.\n\n")
    (OUT / f"{name}.md").write_text(header + body.strip() + "\n", encoding="utf-8")
    write_json(OUT / f"{name}.json", result)
    return result


# --------------------------------------------------------------------- AC-2(3)
def termination():
    terms = read_csv(EV / "AC" / "EVID-003_peoplehub-terminations-2026H1.csv")
    events = {e["target_worker_id"]: e for e in read_csv(EV / "AC" / "EVID-004_okta-deactivation-events-2026H1.csv")}
    creds = read_csv(EV / "IA" / "EVID-007_aws-iam-credential-report_2026-06-30.csv")
    rows = []
    for t in terms:
        eff = _ts(t["termination_date"], t["termination_effective_time"])
        ev = events.get(t["worker_id"])
        if ev:
            lag = (_local(ev["published"]) - eff).total_seconds() / 3600
            status = "Within SLA" if lag <= SLA_H else "Late"
            rows.append({**t, "okta_deactivated": ev["published"][:16], "lag_hours": round(lag, 1), "result": status})
        else:
            rows.append({**t, "okta_deactivated": f"NOT DEACTIVATED (as of {SNAPSHOT})",
                         "lag_hours": "", "result": "Not deactivated"})
    # local-account check: IAM users whose name maps to a terminated worker's login
    logins = {"E1015": "mfeld"}  # from Okta export: login for each terminated worker in scope
    okta = {r["employee_id"]: r["login"] for r in read_csv(ROOT / "access-review" / "source-exports" / "okta_users.csv")}
    logins.update({k: v for k, v in okta.items() if k})
    term_logins = {logins.get(t["worker_id"], "") for t in terms} - {""}
    local_hits = [c for c in creds if any(c["user"].startswith(l + "-") or c["user"] == l for l in term_logins)
                  and (c["password_enabled"] == "true" or c["access_key_1_active"] == "true")]
    res = {
        "population": len(terms),
        "final_pay_refs_present": sum(bool(t["final_pay_or_invoice_ref"]) for t in terms),
        "within_sla": sum(r["result"] == "Within SLA" for r in rows),
        "late": sum(r["result"] == "Late" for r in rows),
        "not_deactivated": sum(r["result"] == "Not deactivated" for r in rows),
        "deactivated": sum(r["result"] != "Not deactivated" for r in rows),
        "local_accounts_active_for_terminated": [c["user"] for c in local_hits],
        "late_or_missing": [f"{r['worker_id']} {r['full_name']} ({r['result']}{', ' + str(r['lag_hours']) + 'h' if r['lag_hours'] != '' else ''})"
                            for r in rows if r["result"] != "Within SLA"],
    }
    res["within_sla_pct"] = round(100 * res["within_sla"] / res["population"])
    body = f"""
**Control:** AC-2(3) Disable Accounts; PS-4 Personnel Termination · **Requirement:** REQ-004 (24-hour de-provisioning), REQ-013
**Evidence:** EVID-003 (PeopleHub terminations, H1 2026), EVID-004 (Okta System Log `user.lifecycle.deactivate`), EVID-007 (AWS IAM credential report)
**Method:** Test (full population of {res['population']} terminations, since the population is under 25)

## IPE check (completeness)
PeopleHub termination count ({res['population']}) reconciled to final-pay or final-invoice references ({res['final_pay_refs_present']} of {res['population']} present). Population accepted as complete.

## Results
| Measure | Result |
|---|---|
| Terminations tested | {res['population']} |
| Okta deactivated within {SLA_H}h | **{res['within_sla']} ({res['within_sla_pct']}%)** |
| Deactivated late | {res['late']} |
| **Not deactivated at snapshot** | **{res['not_deactivated']}** |
| Local (non-SSO) accounts still active for terminated workers | **{len(local_hits)}**: {', '.join(res['local_accounts_active_for_terminated']) or 'none'} |

**Exceptions:** {'; '.join(res['late_or_missing'])}

## Detail
{md_table(rows, ['worker_id', 'full_name', 'worker_type', 'termination_date', 'okta_deactivated', 'lag_hours', 'result'])}

## Conclusion
**Other Than Satisfied.** Expected: 100% of terminated workers lose access within {SLA_H} hours, across SSO and non-SSO accounts. Actual: {res['not_deactivated']} workers were still enabled at the snapshot, 1 was late, and {len(local_hits)} local AWS IAM user outside Okta remained active. Root cause: termination tickets are created manually from an HR email, and local accounts are not on the offboarding checklist. → **FIND-001** / RISK-002 / POAM-001.
"""
    return _write("termination-deprovisioning", "Test Result: Termination De-provisioning (AC-2(3), PS-4)", body, res)


def termination_validation():
    rows = read_csv(EV / "AC" / "EVID-061_terminations-and-deactivations_2026-07-01_to_09-09.csv")
    job = read_csv(EV / "AC" / "EVID-062_hr-okta-reconciliation-job_2026-09-10.csv")
    creds = read_csv(EV / "IA" / "EVID-064_aws-iam-credential-report_2026-09-04.csv")
    out = []
    for r in rows:
        lag = (_local(r["okta_deactivated_at"]) - _ts(r["termination_date"], r["termination_effective_time"])).total_seconds() / 3600
        out.append({**r, "lag_hours": round(lag, 1), "result": "Within SLA" if lag <= SLA_H else "Late"})
    res = {
        "population": len(out),
        "within_sla": sum(o["result"] == "Within SLA" for o in out),
        "max_lag_hours": max(o["lag_hours"] for o in out),
        "automated_tickets": sum("Auto-created" in o["ticket_source"] for o in out),
        "job_runs_reviewed": len(job),
        "job_exceptions_total": sum(int(j["exceptions"]) for j in job),
        "iam_users_remaining": [c["user"] for c in creds if c["user"] != "<root_account>"],
    }
    body = f"""
**Validates:** POAM-001 (FIND-001) · **Evidence:** EVID-061 (Jul–Sep terminations with de-provisioning), EVID-062 (daily HR-to-Okta reconciliation job output), EVID-064 (AWS IAM credential report 2026-09-04)
**Method:** Test (re-performance on all {res['population']} terminations since the fix, plus inspection of {res['job_runs_reviewed']} consecutive job runs)

| Measure | Result |
|---|---|
| Terminations since 2026-07-01 | {res['population']} |
| Okta deactivated within {SLA_H}h | **{res['within_sla']} of {res['population']}** (max lag {res['max_lag_hours']}h) |
| Tickets auto-created by the new job | {res['automated_tickets']} of {res['population']} (the first 2 predate the job go-live on 2026-08-03) |
| Reconciliation job exceptions (5 runs) | {res['job_exceptions_total']} |
| AWS IAM users remaining | {', '.join(res['iam_users_remaining'])} (break-glass only; vaulted, hardware MFA) |

{md_table(out, ['worker_id', 'full_name', 'termination_date', 'okta_deactivated_at', 'lag_hours', 'ticket_source', 'result'])}

## Conclusion
**Remediation validated.** The design gap (manual ticketing, local accounts) is closed, and the operating sample shows 100% within SLA. *Limit:* 7 terminations over 10 weeks is a small operating sample, so AC-2(3) will be re-tested in full at the next annual assessment.
"""
    return _write("termination-deprovisioning-validation", "Validation Re-test: Termination De-provisioning (POAM-001)", body, res)


# ------------------------------------------------------------------------ AU-6
def logreview():
    rows = read_csv(EV / "AU" / "EVID-022_privileged-activity-reviews-2026H1.csv")
    out = []
    for r in rows:
        if not r["ticket"]:
            verdict = "Not performed"
        else:
            late = (dt.date.fromisoformat(r["review_completed"]) - dt.date.fromisoformat(r["week_end"])).days > 5
            complete = r["flagged_items"] == r["flagged_items_dispositioned"] and r["review_notes"].strip().lower() not in ("reviewed", "reviewed - see report")
            verdict = "Performed, incomplete" if not complete else ("Performed, late" if late else "Effective")
        out.append({**r, "verdict": verdict})
    res = {
        "weeks": len(out),
        "performed": sum(o["verdict"] != "Not performed" for o in out),
        "effective": sum(o["verdict"] == "Effective" for o in out),
        "not_performed_weeks": [o["iso_week"] for o in out if o["verdict"] == "Not performed"],
        "incomplete_weeks": [o["iso_week"] for o in out if o["verdict"] == "Performed, incomplete"],
    }
    res["effective_pct"] = round(100 * res["effective"] / res["weeks"])
    body = f"""
**Control:** AU-6 Audit Record Review, Analysis, and Reporting · **Requirement:** REQ-019 (HIPAA audit controls), REQ-005
**Evidence:** EVID-022 (weekly privileged-activity review tickets, W01–W26 2026) · **Method:** Test (all 26 weeks)

**Criteria (from LMS-004 §6):** a review ticket exists for the week, is completed within 5 days of week end, and every flagged item has a documented disposition (a bare "reviewed" does not count).

| Measure | Result |
|---|---|
| Weeks in period | {res['weeks']} |
| Reviews performed | {res['performed']} |
| **Reviews fully effective** | **{res['effective']} ({res['effective_pct']}%)** |
| Weeks with no review | {len(res['not_performed_weeks'])}: {', '.join(res['not_performed_weeks'])} |
| Reviews with undispositioned flags | {len(res['incomplete_weeks'])}: {', '.join(res['incomplete_weeks'])} |

{md_table(out, ['iso_week', 'ticket', 'reviewer', 'review_completed', 'flagged_items', 'flagged_items_dispositioned', 'verdict'])}

## Conclusion
**Other Than Satisfied.** The missed weeks cluster around the SIEM parser migration (W07–W08) and reviewer PTO (W14–W15, W23–W24). There is a single point of failure and no backup reviewer. W13 also shows the review scope excluded local AWS IAM users, which is how the `mfeld-admin` account went unnoticed. → **FIND-009** / RISK-005 / POAM-009.
"""
    return _write("au6-log-review", "Test Result: Privileged-Activity Log Review (AU-6)", body, res)


# ------------------------------------------------------------------ RA-5 / SI-2
def vulnsla():
    rows = read_csv(EV / "RA" / "EVID-048_vuln-remediation-aging-2026H1.csv")
    out = []
    for r in rows:
        first = dt.date.fromisoformat(r["first_detected"])
        days = (dt.date.fromisoformat(r["remediated"]) - first).days if r["remediated"] else (SNAPSHOT - first).days
        out.append({**r, "days": days, "sla_met": "Y" if days <= int(r["sla_days"]) else "N"})
    breached = [o for o in out if o["sla_met"] == "N"]
    open_b = [o for o in breached if o["status"] == "Open"]
    rem = [o["days"] for o in out if o["status"] == "Remediated"]
    res = {
        "population": len(out),
        "critical": sum(o["severity"] == "Critical" for o in out),
        "high": sum(o["severity"] == "High" for o in out),
        "breached": len(breached),
        "breached_pct": round(100 * len(breached) / len(out)),
        "remediated_late": sum(o["status"] == "Remediated" for o in breached),
        "open_past_sla": len(open_b),
        "open_past_sla_critical": sum(o["severity"] == "Critical" for o in open_b),
        "median_days_to_remediate": statistics.median(rem),
        "open_assets": sorted({o["asset"] for o in open_b}),
    }
    body = f"""
**Controls:** RA-5 Vulnerability Monitoring and Scanning; SI-2 Flaw Remediation · **Requirement:** REQ-009 (Critical 15 / High 30 days)
**Evidence:** EVID-048 (scanner export: every Critical/High finding open at any point in H1 2026) · **Method:** Test (full population)

| Measure | Result |
|---|---|
| Critical / High findings in period | {res['population']} ({res['critical']} Critical, {res['high']} High) |
| **Remediated or open beyond SLA** | **{res['breached']} ({res['breached_pct']}%)** |
| Remediated late | {res['remediated_late']} |
| **Open and past SLA at 2026-06-30** | **{res['open_past_sla']}** ({res['open_past_sla_critical']} Critical) on {', '.join(res['open_assets'])} |
| Median days to remediate (closed items) | {res['median_days_to_remediate']} |

### Open past-SLA items
{md_table(open_b, ['vuln_id', 'asset', 'severity', 'title', 'first_detected', 'days', 'exploitable_path_claimed'])}

## Conclusion
**RA-5: Satisfied.** Scanning is authenticated, runs weekly, and covers production images and hosts (7% of resources untagged; see OBS-02). **SI-2: Other Than Satisfied.** 4 of the 6 open breaches sit on **unsupported components** (`wf-sftp-01`, `legacy-reports`) where no vendor patch exists. Patching cannot fix those; they need SA-22 remediation (**FIND-011**). The 2 `notify-worker` criticals are disputed by Engineering as unreachable, but no risk exception was filed as VM-003 §7 requires, so the SLA stands. → **FIND-010** / RISK-006 / POAM-010.
"""
    return _write("si2-vuln-sla", "Test Result: Vulnerability Remediation SLA (RA-5, SI-2)", body, res)


# ------------------------------------------------------------------------ CM-3
def changes():
    rows = read_csv(EV / "CM" / "EVID-030_change-sample-2026H1.csv")
    exc = [r for r in rows if r["assessor_result"].startswith("Exception")]
    res = {
        "population": 212, "sample": len(rows), "sample_seed": 20260618,
        "exceptions": len(exc), "exception_ids": [r["change_id"] for r in exc],
        "emergency_in_sample": sum(r["type"] == "Emergency" for r in rows),
        "emergency_exceptions": sum(r["type"] == "Emergency" for r in exc),
    }
    body = f"""
**Control:** CM-3 Configuration Change Control · **Requirement:** REQ-023 (SOC 2 CC8.1 commitment)
**Evidence:** EVID-030 (production change tickets) · **Method:** Test (random sample of {res['sample']} of {res['population']} production changes, `random.Random({res['sample_seed']})`)

**Criteria:** normal changes are approved *before* deployment. Emergency changes are retro-approved within 2 business days (CMP-006 §4.3). Every change has peer review and test evidence.

| Measure | Result |
|---|---|
| Sample | {res['sample']} of {res['population']} |
| **Exceptions** | **{res['exceptions']}** ({', '.join(res['exception_ids'])}) |
| Emergency changes in sample | {res['emergency_in_sample']} ({res['emergency_exceptions']} with exceptions) |

{md_table(exc, ['change_id', 'type', 'title', 'approved_at', 'deployed_at', 'assessor_result'])}

## Conclusion
**Other Than Satisfied.** 2 of 3 emergency changes in the sample failed the retro-approval standard. One of them (CHG-2026-0412) opened RDP to the internet and was never reverted (**FIND-012**). The pipeline enforces peer review for code, but the **console/manual change path has no preventive gate**. → **FIND-018** / RISK-014 / POAM-018.
"""
    return _write("cm3-change-sample", "Test Result: Change Approval Sample (CM-3)", body, res)


TESTS = {"termination": termination, "termination-validation": termination_validation,
         "logreview": logreview, "vulnsla": vulnsla, "changes": changes}


def run_all():
    results = {k: f() for k, f in TESTS.items()}
    write_json(OUT / "all-results.json", results)
    return results


if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else "all"
    if arg == "all":
        for k, v in run_all().items():
            print(k, {kk: vv for kk, vv in v.items() if not isinstance(vv, list)})
    else:
        print(TESTS[arg]())
