"""Verify every control ID and title in the matrix against NIST's official OSCAL catalog.

The build does not download anything. Obtain the catalog from NIST's official repository:
  https://github.com/usnistgov/oscal-content  ->  nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json

    python tools/verify_catalog.py path/to/NIST_SP-800-53_rev5_catalog.json

Writes docs/assessment/catalog-verification.md. Titles must match exactly (case-sensitive).
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import re
import sys

from build import load_all
from common import ROOT, md_table


def walk(controls, out):
    for c in controls:
        out[c["id"]] = c["title"]
        walk(c.get("controls", []), out)


def oscal_id(cid: str) -> str:
    m = re.fullmatch(r"([A-Z]{2})-(\d+)(?:\((\d+)\))?", cid)
    return f"{m.group(1).lower()}-{m.group(2)}" + (f".{m.group(3)}" if m.group(3) else "")


def main(path):
    raw = open(path, "rb").read()
    cat = json.loads(raw)["catalog"]
    md = cat["metadata"]
    titles = {}
    for g in cat["groups"]:
        walk(g.get("controls", []), titles)
    rows, bad = [], 0
    for c in load_all()["controls"]:
        official = titles.get(oscal_id(c["id"]))
        ok = official == c["name"]
        bad += not ok
        rows.append({"Control": c["id"], "OSCAL ID": oscal_id(c["id"]), "Matrix title": c["name"],
                     "Official title": official or "NOT FOUND", "Match": "✅" if ok else "❌"})
    report = f"""# Control Catalog Verification

> Generated by `tools/verify_catalog.py`. Every control ID and title in the matrix was compared **exactly** (case-sensitive) with NIST's official OSCAL catalog.

| Field | Value |
|---|---|
| Catalog | {md['title']} |
| Catalog version | **{md['version']}** |
| Catalog last-modified | {md['last-modified']} |
| OSCAL version | {md.get('oscal-version', '')} |
| Source | `usnistgov/oscal-content`, `nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json` |
| File SHA-256 | `{hashlib.sha256(raw).hexdigest()}` |
| Controls and enhancements in catalog | {len(titles)} |
| Checked on | {dt.date.today().isoformat()} |
| **Result** | **{len(rows) - bad} of {len(rows)} matrix controls matched exactly; {bad} mismatched** |

{md_table(rows, ["Control", "OSCAL ID", "Matrix title", "Official title", "Match"])}
"""
    (ROOT / "docs" / "assessment" / "catalog-verification.md").write_text(report, encoding="utf-8")
    for r in rows:
        if r["Match"] != "✅":
            print(f"MISMATCH {r['Control']}: matrix='{r['Matrix title']}' official='{r['Official title']}'")
    print(f"catalog version {md['version']}: {len(rows) - bad} matched exactly, {bad} mismatched")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    main(sys.argv[1])
